### ISSUE TITLE
backbone-couch.js throws 'undefined is not a function' error

### ISSUE THREAD

**Issue by thewildpendulum** [cutting-room-floor/backbone-couch#8]
I apologize if this isn't issue-worthy, but I can't figure out anywhere else to ask this question, so I'm creating an issue around it.

I have a small bones app that I'm trying use backbone-couch with, but whenever I call .save(), I get this error:

```
/vagrant/lgt-tim/node_modules/backbone-couch/backbone-couch.js:88
    if (err) return error(err);
                    ^
TypeError: undefined is not a function
```

I have no idea why this happens. I basically c/p'ed the code from the readme and nothing seems to be wrong. I've uninstalled and reinstalled. I have couchdb running. I'm out ideas. Help?

**Comment by tmcw** [comment]
Are you using bones 1.x or 2.x? I don't think this module is compatible with 2.x yet.

**Comment by thewildpendulum** [comment]
That's likely the problem. I'm on 2.0.0alpha4. Thanks for the response. I'll open an issue for bones 2.x support.
